outplacement_final_report AFC-1933: fixed study visit GUI
vertelab/odoo-outplacement pull request #145
Opened 2021-03-12 08:15 UTC by SebastianGieser-Vertel

2021-03-17 14:37 UTC, nils-vertel requested changes
Some translations seems a bit off to me, check with Tim for second opinion if he approve merge it.

2021-03-17 14:37 UTC, nils-vertel commented on outplacement_final_report/i18n/sv_SE.po
> +msgstr ""
Missing translation?

2021-03-17 14:37 UTC, nils-vertel commented on outplacement_final_report/i18n/sv_SE.po
> +#. module: outplacement_final_report
deltagare mål, deltagare mål steg, deltagare studiebesök feels off, please consider rephrasing.

2021-03-17 15:31 UTC, timforsstromAF commented on outplacement_final_report/i18n/sv_SE.po
> +msgstr ""
Yes, added that :)

2021-03-17 15:36 UTC, timforsstromAF commented on outplacement_final_report/i18n/sv_SE.po
> +#. module: outplacement_final_report
förslag: deltagarens mål, deltagaranes delmål, deltagarens studiebesök?

2021-03-17 15:40 UTC, timforsstromAF commented
Change translations as suggested and its ok with me.

2021-03-18 15:38 UTC, nils-vertel approved these changes

2021-03-18 15:39 UTC, merged