AFC-2125 Odoo Tray-widget for Interpreter
vertelab/odoo-outplacement pull request #208
Opened 2021-05-04 18:51 UTC by iammiracle

2021-05-17 14:04 UTC, nils-vertel requested changes
Some fixes still needed, see comments.

Additional columns for the canban view:

- Deltagarnamn (partner_name)
- Akt-nummer (file_reference_number?) (check with Fredrik)
- Genomförande referens (interpreter_booking_ref?) (check with Fredrik)

Remove date for endtime on canbanview

Also this pull request seems to be dependent on https://github.com/vertelab/odoo-base/pull/304

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/mail_activity.py
> +from collections import defaultdict
Imports are wrongly sorted
collections shall be imported before datetime

pytz and odoo is thirdparty imports and thus shall be grouped seperatly from Python builtins.

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received',
activity.active == True and ... can be replaced with activity.active and ...?
Same for all similar constructs here
The field _interpreter_booking_status only has the values ('1', '2') so no need to check for the text variants.
The field _interpreter_booking_status only has the values ('1', '2', '3', '4', '5', '6') so no need to check for the text variants.

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/mail_activity.py
> +            [('code', '=', data.get('tolkTypId'))])  # noqa:E501
The # noqa:E501 can be removed from these lines if they are no longer to long

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received', 'Order mottagen'] \
if activity.active and ... should be enough?
_interpreter_booking_status can only have ('1', '2') as values
_interpreter_booking_status_2 can only have ('1', '2', '3', '4', '5', '6') as values
Unnecessary to check for the readable values as they are only in self.interpreter_booking_status field.

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/mail_activity.py
> +    def _compute_activity_status(self):
Is this needed as there is already a interpreter_booking_status field that contains mostly the same info?
Checking the code it might be needed but check the already defined field and think about it

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/res_users.py
> +                                   AND act._interpreter_booking_status_2  = ANY (ARRAY['4','Interpreter Booked', 'Tolk bokad'])
See earlier comments on valid values of this field

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/res_users.py
> +        model_names = {n[0]: n[1] for n in self.env['ir.model'].browse(model_ids).name_get()}
This line is a bit long

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/res_users.py
> +                    'icon': modules.module.get_module_icon(self.env[activity['model']]._original_module),
This line is a bit long

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/res_users.py
> +                user_activities[activity['model']]['%s_count' % activity['states']] += activity['count']
This line is a bit long

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/static/src/xml/booking_activity.xml
> +                        <!--                        <span t-if="!activity.active_booking_count" class="o_no_activity mr16">0 Bookings </span>-->
Commented code, either add a comment on why its to be kept or remove it

2021-05-17 14:04 UTC, nils-vertel commented on outplacement_order_interpreter/models/res_users.py
> +            if task.outplacement_id:
This crashes if there exists an orphan mail_activity.
If parent task has been deleted but the activity still exist.
Please add additional safeguard here

2021-05-18 06:44 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +from collections import defaultdict
@nils-vertel Ok I will check about collections. I have added 'base_user_groups_dafa' module in depends in manifest. Should I need to add PR link in description?

2021-05-18 06:47 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received',
Ok @nils-vertel I will update.

2021-05-18 06:48 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +            [('code', '=', data.get('tolkTypId'))])  # noqa:E501
Ok @nils-vertel

2021-05-18 06:48 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received', 'Order mottagen'] \
Ok @nils-vertel

2021-05-18 06:50 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +    def _compute_activity_status(self):
@nils-vertel This is needed as new field is depends on these 4 fields.

2021-05-18 06:50 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                                   AND act._interpreter_booking_status_2  = ANY (ARRAY['4','Interpreter Booked', 'Tolk bokad'])
Ok @nils-vertel

2021-05-18 06:50 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +        model_names = {n[0]: n[1] for n in self.env['ir.model'].browse(model_ids).name_get()}
Ok I will check it @nils-vertel

2021-05-18 06:51 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                    'icon': modules.module.get_module_icon(self.env[activity['model']]._original_module),
Ok I will check it @nils-vertel

2021-05-18 06:51 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                user_activities[activity['model']]['%s_count' % activity['states']] += activity['count']
Ok I will check it @nils-vertel

2021-05-18 06:51 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/static/src/xml/booking_activity.xml
> +                        <!--                        <span t-if="!activity.active_booking_count" class="o_no_activity mr16">0 Bookings </span>-->
Ok @nils-vertel

2021-05-18 06:53 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +            if task.outplacement_id:
Can you please explain me with example? @nils-vertel

2021-05-18 07:35 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                                   AND act._interpreter_booking_status_2  = ANY (ARRAY['4','Interpreter Booked', 'Tolk bokad'])
@nils-vertel This is Postgresql query so I think here should be write TRUE/FALSE

2021-05-18 07:36 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +        model_names = {n[0]: n[1] for n in self.env['ir.model'].browse(model_ids).name_get()}
This link is not log I check in Pycharm editor. @nils-vertel

2021-05-18 07:36 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                    'icon': modules.module.get_module_icon(self.env[activity['model']]._original_module),
This link is not log I check in Pycharm editor. @nils-vertel

2021-05-18 07:37 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/res_users.py
> +                user_activities[activity['model']]['%s_count' % activity['states']] += activity['count']
This link is not log I check in Pycharm editor. @nils-vertel

2021-05-18 07:47 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +from collections import defaultdict
@nils-vertel Done changes related to new fields on Kanban view and Collection library in https://github.com/vertelab/odoo-outplacement/commit/29c504f323e34a8a8b63383fdd04d1e84adc1df6. waiting for dependency reply.

2021-05-18 07:47 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received',
Done in https://github.com/vertelab/odoo-outplacement/commit/29c504f323e34a8a8b63383fdd04d1e84adc1df6

2021-05-18 07:48 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +            [('code', '=', data.get('tolkTypId'))])  # noqa:E501
@nils-vertel Done in https://github.com/vertelab/odoo-outplacement/commit/29c504f323e34a8a8b63383fdd04d1e84adc1df6

2021-05-18 07:48 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/models/mail_activity.py
> +                    if activity.active == True and activity._interpreter_booking_status in ['1', 'Order received', 'Order mottagen'] \
@nils-vertel Done in https://github.com/vertelab/odoo-outplacement/commit/29c504f323e34a8a8b63383fdd04d1e84adc1df6

2021-05-18 07:49 UTC, rupareliyahemangi145 commented on outplacement_order_interpreter/static/src/xml/booking_activity.xml
> +                        <!--                        <span t-if="!activity.active_booking_count" class="o_no_activity mr16">0 Bookings </span>-->
@nils-vertel Done in https://github.com/vertelab/odoo-outplacement/commit/29c504f323e34a8a8b63383fdd04d1e84adc1df6

2021-05-19 11:03 UTC, merged