12.0 fix order interpreter cron
vertelab/odoo-outplacement pull request #301
Opened 2021-08-30 14:27 UTC by SebastianGieser-Vertel

2021-08-30 14:59 UTC, fredrikarvas-vertel approved these changes
This looks good to me.

2021-08-31 09:44 UTC, fredrikarvas-vertel requested changes
Please add a Jira and change the header to invoice. I do not think it has to do with interpreter.

2021-09-01 05:59 UTC, draal-af requested changes

2021-09-01 05:59 UTC, draal-af commented on outplacement_invoice/__manifest__.py
> +        'data/server_action.xml'
Are we missing the data file?

2021-09-02 08:05 UTC, S-Arnshed-Capgemini approved these changes

2021-09-02 08:06 UTC, merged

2021-09-02 09:57 UTC, nils-vertel commented on outplacement_invoice/data/server_action.xml
> +for order in env['sale.order'].search([]):
Commented code, please write a line on why we need to keep it